# -*- coding: utf-8 -*-
"""Model Deployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-GSK_D1zPUwWNTDJTWeX_zcOHgKqDsNz
"""

import pandas as pd
from statsmodels.tsa.ar_model import AutoReg

def predict():
  data = pd.read_csv('items.csv')
  dataT = data.T
  item1 = dataT.iloc[1:,1]
  # split dataset
  X = item1.values
  train, test = X[1:len(X)-7], X[len(X)-7:]
  # train autoregression
  model = AutoReg(train, lags=14)
  model_fit = model.fit()
  # make predictions
  predictions = model_fit.predict(start=len(train), end=len(train)+len(test)-1, dynamic=False)
  print(predictions)

predict()

pip freeze > requirements.txt